package br.com.mario.cadastro.modelo;

// Generated 16/05/2015 14:37:37 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Vendedor generated by hbm2java
 */
@Entity
@Table(name = "VENDEDOR", catalog = "cadastro")
public class Vendedor implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1560014008676675299L;
	private int pesId;
	private Pessoa pessoa;
	private String venDescricao;
	private Set<Cliente> clientes = new HashSet<Cliente>(0);

	public Vendedor() {
	}

	public Vendedor(Pessoa pessoa) {
		this.pessoa = pessoa;
	}

	public Vendedor(Pessoa pessoa, String venDescricao, Set<Cliente> clientes) {
		this.pessoa = pessoa;
		this.venDescricao = venDescricao;
		this.clientes = clientes;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "pessoa"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "PES_ID", unique = true, nullable = false)
	public int getPesId() {
		return this.pesId;
	}

	public void setPesId(int pesId) {
		this.pesId = pesId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Pessoa getPessoa() {
		return this.pessoa;
	}

	public void setPessoa(Pessoa pessoa) {
		this.pessoa = pessoa;
	}

	@Column(name = "VEN_DESCRICAO", length = 150)
	public String getVenDescricao() {
		return this.venDescricao;
	}

	public void setVenDescricao(String venDescricao) {
		this.venDescricao = venDescricao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vendedor")
	public Set<Cliente> getClientes() {
		return this.clientes;
	}

	public void setClientes(Set<Cliente> clientes) {
		this.clientes = clientes;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((clientes == null) ? 0 : clientes.hashCode());
		result = prime * result + pesId;
		result = prime * result + ((pessoa == null) ? 0 : pessoa.hashCode());
		result = prime * result
				+ ((venDescricao == null) ? 0 : venDescricao.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Vendedor other = (Vendedor) obj;
		if (clientes == null) {
			if (other.clientes != null)
				return false;
		} else if (!clientes.equals(other.clientes))
			return false;
		if (pesId != other.pesId)
			return false;
		if (pessoa == null) {
			if (other.pessoa != null)
				return false;
		} else if (!pessoa.equals(other.pessoa))
			return false;
		if (venDescricao == null) {
			if (other.venDescricao != null)
				return false;
		} else if (!venDescricao.equals(other.venDescricao))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Vendedor [pesId=" + pesId + "]";
	}

}
